Add continue-on-error + handle script assert

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -196,6 +196,7 @@ jobs:
           rm artifacts.tar.gz
           mv cache current
       - name: Compare artifacts
+        continue-on-error: true
         run: |
           python3 python/test/tools/compare_files.py --path1 reference --path2 current --kernels python/test/kernel_comparison/kernels.yml
           exit_code=$?
@@ -209,6 +210,11 @@ jobs:
             echo "Error while comparing artifacts"
             echo "COMPARISON_RESULT=error" >> $GITHUB_STATE
           fi
+      - name: Check exit code and handle failure
+        if: ${{ env.COMPARISON_RESULT == 'error' }}
+        run: |
+          echo "Error while comparing artifacts"
+          exit 1
       - name: Fetch Run ID
         id: get_run_id
         run: echo "RUN_ID=${{ github.run_id }}" >> $GITHUB_STATE
