initial code merge of Hopper support (#52)
Co-authored-by: Goostav Zhu <gzhu@nvidia.com>

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -3,9 +3,9 @@ name: Integration Tests
 on:
   workflow_dispatch:
   pull_request:
-    branches: [main]
+    branches: [main, hopper_merge]
   merge_group:
-    branches: [main]
+    branches: [main, hopper_merge]
     types: [checks_requested]
 
 concurrency:
@@ -25,9 +25,8 @@ jobs:
       - name: Prepare runner matrix
         id: set-matrix
         run: |
-          if [ x"${{ github.repository }}" == x"openai/triton" ]; then
-            echo '::set-output name=matrix-required::[["self-hosted", "A100"], ["self-hosted", "H100"]]'
-            echo '::set-output name=matrix-optional::[["self-hosted", "gfx908"], ["self-hosted", "arc770"]]'
+          if [ x"${{ github.repository }}" == x"openai/triton-hopper" ]; then
+            echo '::set-output name=matrix-required::[["self-hosted", "H100"]]'
           else
             echo '::set-output name=matrix-required::["ubuntu-latest"]'
             echo '::set-output name=matrix-optional::["ubuntu-latest"]'
@@ -50,6 +49,8 @@ jobs:
         if: ${{(matrix.runner[0] == 'self-hosted') && (matrix.runner[1] == 'V100' || matrix.runner[1] == 'A100' || matrix.runner[1] == 'H100')}}
         run: |
           echo "BACKEND=CUDA" >> "${GITHUB_ENV}"
+          echo "ENABLE_TMA=0" >> "${GITHUB_ENV}"
+          echo "ENABLE_MMA_V3=0" >> "${GITHUB_ENV}"
 
       - name: Clear cache
         run: |
@@ -79,8 +80,32 @@ jobs:
           fi
           lit -v "${LIT_TEST_DIR}"
 
-      - name: Run python tests on CUDA
-        if: ${{ env.BACKEND == 'CUDA'}}
+      - name: Enable MMAV3 and TMA
+        if: ${{(matrix.runner[0] == 'self-hosted') && (matrix.runner[1] == 'H100')}}
+        run: |
+          echo "ENABLE_TMA=1" >> "${GITHUB_ENV}"
+          echo "ENABLE_MMA_V3=1" >> "${GITHUB_ENV}"
+
+      - name: Run python tests on CUDA with ENABLE_TMA=1 and ENABLE_MMA_V3=1
+        if: ${{ env.BACKEND == 'CUDA' && env.ENABLE_TMA == '1' && env.ENABLE_MMA_V3 == '1'}}
+        run: |
+          cd python/test/unit
+          python3 -m pytest -n 8 --ignore=runtime
+          # run runtime tests serially to avoid race condition with cache handling.
+          python3 -m pytest runtime/
+
+      - name: Disable MMAV3 and TMA
+        if: ${{(matrix.runner[0] == 'self-hosted') && (matrix.runner[1] == 'H100')}}
+        run: |
+          echo "ENABLE_TMA=0" >> "${GITHUB_ENV}"
+          echo "ENABLE_MMA_V3=0" >> "${GITHUB_ENV}"
+
+      - name: Clear cache
+        run: |
+          rm -rf ~/.triton
+
+      - name: Run python tests on CUDA with ENABLE_TMA=0 and ENABLE_MMA_V3=0
+        if: ${{ env.BACKEND == 'CUDA' && env.ENABLE_TMA == '0' && env.ENABLE_MMA_V3 == '0'}}
         run: |
           cd python/test/unit
           python3 -m pytest -n 8 --ignore=runtime
@@ -202,135 +227,135 @@ jobs:
           cd python/test/backend/third_party_backends
           python3 -m pytest --capture=tee-sys -rfs --verbose --backend xpu
 
-  Compare-artifacts:
-    needs: Integration-Tests-Nvidia
+  # Compare-artifacts:
+  #   needs: Integration-Tests-Nvidia
 
-    runs-on: ubuntu-latest
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v2
 
-      - name: Install gh CLI
-        run: |
-          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 23F3D4EA75716059
-          echo "deb [arch=$(dpkg --print-architecture)] https://cli.github.com/packages focal main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
-          sudo apt update
-          sudo apt install gh
+  #     - name: Install gh CLI
+  #       run: |
+  #         sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 23F3D4EA75716059
+  #         echo "deb [arch=$(dpkg --print-architecture)] https://cli.github.com/packages focal main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
+  #         sudo apt update
+  #         sudo apt install gh
 
-      - name: Download latest main artifacts
-        env:
-          ARTIFACT_NAME: artifacts A100
-          ARTIFACT_JOB_NAME: Integration-Tests-Nvidia
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          OWNER_REPO="${{ github.repository }}"
-          echo "OWNER_REPO: $OWNER_REPO"
-          PR_NUMBERS=($(gh api --method GET repos/$OWNER_REPO/pulls -f state=closed | jq -r ".[] | select(.merged_at != null) | .number"))
+  #     - name: Download latest main artifacts
+  #       env:
+  #         ARTIFACT_NAME: artifacts A100
+  #         ARTIFACT_JOB_NAME: Integration-Tests-Nvidia
+  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       run: |
+  #         OWNER_REPO="${{ github.repository }}"
+  #         echo "OWNER_REPO: $OWNER_REPO"
+  #         PR_NUMBERS=($(gh api --method GET repos/$OWNER_REPO/pulls -f state=closed | jq -r ".[] | select(.merged_at != null) | .number"))
 
-          # Not all PRs go through integration tests
-          success=0
-          for PR_NUMBER in "${PR_NUMBERS[@]}"
-          do
-            echo "Last merged PR number: $PR_NUMBER"
-            BRANCH_NAME=$(gh api repos/$OWNER_REPO/pulls/$PR_NUMBER --jq '.head.ref')
-            echo "BRANCH_NAME: $BRANCH_NAME"
-            USER_ID=$(gh api repos/$OWNER_REPO/pulls/$PR_NUMBER --jq '.user.id')
-            echo "USER_ID: $USER_ID"
+  #         # Not all PRs go through integration tests
+  #         success=0
+  #         for PR_NUMBER in "${PR_NUMBERS[@]}"
+  #         do
+  #           echo "Last merged PR number: $PR_NUMBER"
+  #           BRANCH_NAME=$(gh api repos/$OWNER_REPO/pulls/$PR_NUMBER --jq '.head.ref')
+  #           echo "BRANCH_NAME: $BRANCH_NAME"
+  #           USER_ID=$(gh api repos/$OWNER_REPO/pulls/$PR_NUMBER --jq '.user.id')
+  #           echo "USER_ID: $USER_ID"
 
-            page=1
-            while true; do
-              run_id=$(gh api --method GET "repos/$OWNER_REPO/actions/runs?page=$page&per_page=100" | jq --arg branch_name "$BRANCH_NAME" --arg run_name "Integration Tests" --arg user_id "$USER_ID" '.workflow_runs[] | select(.head_branch == $branch_name and .name == $run_name and .actor.id == ($user_id | tonumber))' | jq '.id' | head -1)
-              if [ "$run_id" != "" ]; then
-                echo "First run ID on branch $BRANCH_NAME is: $run_id"
-                WORKFLOW_RUN_ID=$run_id
-                break
-              fi
+  #           page=1
+  #           while true; do
+  #             run_id=$(gh api --method GET "repos/$OWNER_REPO/actions/runs?page=$page&per_page=100" | jq --arg branch_name "$BRANCH_NAME" --arg run_name "Integration Tests" --arg user_id "$USER_ID" '.workflow_runs[] | select(.head_branch == $branch_name and .name == $run_name and .actor.id == ($user_id | tonumber))' | jq '.id' | head -1)
+  #             if [ "$run_id" != "" ]; then
+  #               echo "First run ID on branch $BRANCH_NAME is: $run_id"
+  #               WORKFLOW_RUN_ID=$run_id
+  #               break
+  #             fi
 
-              ((page++))
-            done
+  #             ((page++))
+  #           done
 
-            echo "WORKFLOW_RUN_ID: $WORKFLOW_RUN_ID"
-            ARTIFACT_URL=$(gh api repos/$OWNER_REPO/actions/runs/$WORKFLOW_RUN_ID/artifacts | jq --arg artifact_name "$ARTIFACT_NAME" '.artifacts[] | select(.name == $artifact_name).archive_download_url' --raw-output)
-            echo "ARTIFACT_URL: $ARTIFACT_URL"
+  #           echo "WORKFLOW_RUN_ID: $WORKFLOW_RUN_ID"
+  #           ARTIFACT_URL=$(gh api repos/$OWNER_REPO/actions/runs/$WORKFLOW_RUN_ID/artifacts | jq --arg artifact_name "$ARTIFACT_NAME" '.artifacts[] | select(.name == $artifact_name).archive_download_url' --raw-output)
+  #           echo "ARTIFACT_URL: $ARTIFACT_URL"
 
-            if [ -n "$ARTIFACT_URL" ]; then
-              echo "Downloading artifact: $ARTIFACT_URL"
-              curl --location --remote-header-name -H "Authorization: token $GH_TOKEN" -o reference.zip "$ARTIFACT_URL"
-              # Print the size of the downloaded artifact
-              echo "Artifact size (stat): $(stat --printf="%s bytes" reference.zip)"
-              echo "Artifact size (du): $(du -sh reference.zip)"
-              unzip reference.zip
-              tar -xzf artifacts.tar.gz
-              rm reference.zip
-              rm artifacts.tar.gz
-              mv cache reference
-              success=1
-              break
-            fi
-          done
+  #           if [ -n "$ARTIFACT_URL" ]; then
+  #             echo "Downloading artifact: $ARTIFACT_URL"
+  #             curl --location --remote-header-name -H "Authorization: token $GH_TOKEN" -o reference.zip "$ARTIFACT_URL"
+  #             # Print the size of the downloaded artifact
+  #             echo "Artifact size (stat): $(stat --printf="%s bytes" reference.zip)"
+  #             echo "Artifact size (du): $(du -sh reference.zip)"
+  #             unzip reference.zip
+  #             tar -xzf artifacts.tar.gz
+  #             rm reference.zip
+  #             rm artifacts.tar.gz
+  #             mv cache reference
+  #             success=1
+  #             break
+  #           fi
+  #         done
 
-          if [ $success -eq 0 ]; then
-            echo "No artifact found with the name: $ARTIFACT_NAME"
-            exit 1
-          fi
-      - name: Download current job artifacts
-        uses: actions/download-artifact@v2
-        with:
-          name: artifacts A100
-      - name: Unzip current job artifacts
-        run: |
-          # Print the size of the downloaded artifact
-          echo "Artifact size (stat): $(stat --printf="%s bytes" artifacts.tar.gz)"
-          echo "Artifact size (du): $(du -sh artifacts.tar.gz)"
-          tar -xzf artifacts.tar.gz
-          rm artifacts.tar.gz
-          mv cache current
-      - name: Compare artifacts
-        run: |
-          set +e
-          python3 python/test/tools/compare_files.py --path1 reference --path2 current --kernels python/test/kernel_comparison/kernels.yml
-          exit_code=$?
-          set -e
-          echo $exit_code
-          if [ $exit_code -eq 0 ]; then
-            echo "Artifacts are identical"
-            echo "COMPARISON_RESULT=true" >> $GITHUB_ENV
-          elif [ $exit_code -eq 1 ]; then
-            echo "Artifacts are different"
-            echo "COMPARISON_RESULT=false" >> $GITHUB_ENV
-          else
-            echo "Error while comparing artifacts"
-            echo "COMPARISON_RESULT=error" >> $GITHUB_ENV
-          fi
-          echo "COMPARISON_RESULT=env.COMPARISON_RESULT"
-      - name: Check exit code and handle failure
-        if: ${{ env.COMPARISON_RESULT == 'error' }}
-        run: |
-          echo "Error while comparing artifacts"
-          exit 1
-      - name: Fetch Run ID
-        id: get_run_id
-        run: echo "RUN_ID=${{ github.run_id }}" >> $GITHUB_ENV
+  #         if [ $success -eq 0 ]; then
+  #           echo "No artifact found with the name: $ARTIFACT_NAME"
+  #           exit 1
+  #         fi
+  #     - name: Download current job artifacts
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: artifacts A100
+  #     - name: Unzip current job artifacts
+  #       run: |
+  #         # Print the size of the downloaded artifact
+  #         echo "Artifact size (stat): $(stat --printf="%s bytes" artifacts.tar.gz)"
+  #         echo "Artifact size (du): $(du -sh artifacts.tar.gz)"
+  #         tar -xzf artifacts.tar.gz
+  #         rm artifacts.tar.gz
+  #         mv cache current
+  #     - name: Compare artifacts
+  #       run: |
+  #         set +e
+  #         python3 python/test/tools/compare_files.py --path1 reference --path2 current --kernels python/test/kernel_comparison/kernels.yml
+  #         exit_code=$?
+  #         set -e
+  #         echo $exit_code
+  #         if [ $exit_code -eq 0 ]; then
+  #           echo "Artifacts are identical"
+  #           echo "COMPARISON_RESULT=true" >> $GITHUB_ENV
+  #         elif [ $exit_code -eq 1 ]; then
+  #           echo "Artifacts are different"
+  #           echo "COMPARISON_RESULT=false" >> $GITHUB_ENV
+  #         else
+  #           echo "Error while comparing artifacts"
+  #           echo "COMPARISON_RESULT=error" >> $GITHUB_ENV
+  #         fi
+  #         echo "COMPARISON_RESULT=env.COMPARISON_RESULT"
+  #     - name: Check exit code and handle failure
+  #       if: ${{ env.COMPARISON_RESULT == 'error' }}
+  #       run: |
+  #         echo "Error while comparing artifacts"
+  #         exit 1
+  #     - name: Fetch Run ID
+  #       id: get_run_id
+  #       run: echo "RUN_ID=${{ github.run_id }}" >> $GITHUB_ENV
 
-      - name: Upload results as artifact
-        uses: actions/upload-artifact@v2
-        with:
-          name: kernels-reference-check
-          path: kernels_reference_check.txt
+  #     - name: Upload results as artifact
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: kernels-reference-check
+  #         path: kernels_reference_check.txt
 
-      - name: Check output and comment on PR
-        if: ${{ env.COMPARISON_RESULT == 'false' }}
-        uses: actions/github-script@v5
-        with:
-          github-token: ${{ secrets.CI_ACCESS_TOKEN }}
-          script: |
-            const run_id = ${{ env.RUN_ID }};
-            const issue_number = context.payload.pull_request.number;
-            const message = `:warning: **This PR does not produce bitwise identical kernels as the branch it's merged against.** Please check artifacts for details. [Download the output file here](https://github.com/${{ github.repository }}/actions/runs/${run_id}).`;
-            await github.rest.issues.createComment({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                issue_number: issue_number,
-                body: message
-            });
+  #     - name: Check output and comment on PR
+  #       if: ${{ env.COMPARISON_RESULT == 'false' }}
+  #       uses: actions/github-script@v5
+  #       with:
+  #         github-token: ${{ secrets.CI_ACCESS_TOKEN }}
+  #         script: |
+  #           const run_id = ${{ env.RUN_ID }};
+  #           const issue_number = context.payload.pull_request.number;
+  #           const message = `:warning: **This PR does not produce bitwise identical kernels as the branch it's merged against.** Please check artifacts for details. [Download the output file here](https://github.com/${{ github.repository }}/actions/runs/${run_id}).`;
+  #           await github.rest.issues.createComment({
+  #               owner: context.repo.owner,
+  #               repo: context.repo.repo,
+  #               issue_number: issue_number,
+  #               body: message
+  #           });
