[CI] Added IR reference-check github workflow (#1755)

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -173,3 +173,110 @@ jobs:
           sudo nvidia-smi -i 0 --lock-gpu-clocks=1350,1350
           python3 -m pytest -vs .
           sudo nvidia-smi -i 0 -rgc
+
+  Compare-artifacts:
+    needs: Integration-Tests
+
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Install gh CLI
+        run: |
+          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 23F3D4EA75716059
+          echo "deb [arch=$(dpkg --print-architecture)] https://cli.github.com/packages focal main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
+          sudo apt update
+          sudo apt install gh
+
+      - name: Download latest main artifacts
+        env:
+          ARTIFACT_NAME: artifacts A100
+          ARTIFACT_JOB_NAME: Integration-Tests
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          OWNER_REPO="${{ github.repository }}"
+          PR_NUMBER=$(gh api --method GET repos/$OWNER_REPO/pulls -f state=closed | jq ".[] | select(.merged_at != null) | .number" | head -1)
+          echo "Last merged PR number: $PR_NUMBER"
+
+          BRANCH_NAME=$(gh api repos/$OWNER_REPO/pulls/$PR_NUMBER --jq '.head.ref')
+          echo "BRANCH_NAME: $BRANCH_NAME"
+          WORKFLOW_RUN_ID=$(gh api --method GET repos/$OWNER_REPO/actions/runs | jq --arg branch_name "$BRANCH_NAME" '.workflow_runs[] | select(.head_branch == $branch_name)' | jq '.id' | head -1)
+          echo "WORKFLOW_RUN_ID: $WORKFLOW_RUN_ID"
+          ARTIFACT_URL=$(gh api repos/$OWNER_REPO/actions/runs/$WORKFLOW_RUN_ID/artifacts | jq --arg artifact_name "$ARTIFACT_NAME" '.artifacts[] | select(.name == $artifact_name).archive_download_url' --raw-output)
+          echo "ARTIFACT_URL: $ARTIFACT_URL"
+
+          if [ -n "$ARTIFACT_URL" ]; then
+            echo "Downloading artifact: $ARTIFACT_URL"
+            curl --location --remote-header-name -H "Authorization: token $GH_TOKEN" -o reference.zip "$ARTIFACT_URL"
+            # Print the size of the downloaded artifact
+            echo "Artifact size (stat): $(stat --printf="%s bytes" reference.zip)"
+            echo "Artifact size (du): $(du -sh reference.zip)"
+            unzip reference.zip
+            tar -xzf artifacts.tar.gz
+            rm reference.zip
+            rm artifacts.tar.gz
+            mv cache reference
+          else
+            echo "No artifact found with the name: $ARTIFACT_NAME"
+          fi
+      - name: Download current job artifacts
+        uses: actions/download-artifact@v2
+        with:
+          name: artifacts A100
+      - name: Unzip current job artifacts
+        run: |
+          # Print the size of the downloaded artifact
+          echo "Artifact size (stat): $(stat --printf="%s bytes" artifacts.tar.gz)"
+          echo "Artifact size (du): $(du -sh artifacts.tar.gz)"
+          tar -xzf artifacts.tar.gz
+          rm artifacts.tar.gz
+          mv cache current
+      - name: Compare artifacts
+        run: |
+          set +e
+          python3 python/test/tools/compare_files.py --path1 reference --path2 current --kernels python/test/kernel_comparison/kernels.yml
+          exit_code=$?
+          set -e
+          echo $exit_code
+          if [ $exit_code -eq 0 ]; then
+            echo "Artifacts are identical"
+            echo "COMPARISON_RESULT=true" >> $GITHUB_ENV
+          elif [ $exit_code -eq 1 ]; then
+            echo "Artifacts are different"
+            echo "COMPARISON_RESULT=false" >> $GITHUB_ENV
+          else
+            echo "Error while comparing artifacts"
+            echo "COMPARISON_RESULT=error" >> $GITHUB_ENV
+          fi
+          echo "COMPARISON_RESULT=env.COMPARISON_RESULT"
+      - name: Check exit code and handle failure
+        if: ${{ env.COMPARISON_RESULT == 'error' }}
+        run: |
+          echo "Error while comparing artifacts"
+          exit 1
+      - name: Fetch Run ID
+        id: get_run_id
+        run: echo "RUN_ID=${{ github.run_id }}" >> $GITHUB_ENV
+
+      - name: Upload results as artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: kernels-reference-check
+          path: kernels_reference_check.txt
+
+      - name: Check output and comment on PR
+        if: ${{ env.COMPARISON_RESULT == 'false' }}
+        uses: actions/github-script@v5
+        with:
+          script: |
+            const run_id = ${{ env.RUN_ID }};
+            const issue_number = context.payload.pull_request.number;
+            const message = `:warning: **This PR does not produce bitwise identical kernels as the branch it's merged against.** Please check artifacts for details. [Download the output file here](https://github.com/${{ github.repository }}/actions/runs/${run_id}).`;
+            await github.rest.issues.createComment({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                issue_number: issue_number,
+                body: message
+            });
