Some more changes

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -197,9 +197,18 @@ jobs:
           mv cache current
       - name: Compare artifacts
         run: |
-          output=$(python3 python/test/tools/compare_files.py --path1 reference --path2 current --kernels python/test/kernel_comparison/kernels.yml)
-          echo "COMPARISON_RESULT=$output" >> $GITHUB_STATE
-
+          python3 python/test/tools/compare_files.py --path1 reference --path2 current --kernels python/test/kernel_comparison/kernels.yml
+          exit_code=$?
+          if [ $exit_code -eq 0 ]; then
+            echo "Artifacts are identical"
+            echo "COMPARISON_RESULT=true" >> $GITHUB_STATE
+          elif [$exit_code -eq 1 ]; then
+            echo "Artifacts are different"
+            echo "COMPARISON_RESULT=false" >> $GITHUB_STATE
+          else
+            echo "Error while comparing artifacts"
+            echo "COMPARISON_RESULT=error" >> $GITHUB_STATE
+          fi
       - name: Fetch Run ID
         id: get_run_id
         run: echo "RUN_ID=${{ github.run_id }}" >> $GITHUB_STATE
