[CI][AMD]Clean up ~/.triton after a failed build

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -361,6 +361,12 @@ jobs:
           pip uninstall -y triton
           cd python
           pip install -v -e '.[tests]'
+          echo "Artificial erroring out"
+          exit 1
+      - name: Clean up after a failed build
+        if: failure()
+        run: |
+          rm -rf ~/.triton
       - name: Run lit tests
         run: |
           cd python
@@ -415,8 +421,7 @@ jobs:
           du -sh ~/.cache/ccache
       - name: Clean up caches
         run: |
-          rm -rf ~/.triton
-          rm -rf ~/.cache
+          rm -rf ~/.triton/cache
   Build-Tests:
     needs: Runner-Preparation
     if: needs.Runner-Preparation.outputs.matrix-MACOS != ''
diff --git a/.github/workflows/integration-tests.yml.in b/.github/workflows/integration-tests.yml.in
--- a/.github/workflows/integration-tests.yml.in
+++ b/.github/workflows/integration-tests.yml.in
@@ -373,6 +373,13 @@ jobs:
           pip uninstall -y triton
           cd python
           pip install -v -e '.[tests]'
+          echo "Artificial erroring out"
+          exit 1
+
+      - name: Clean up after a failed build
+        if: failure()
+        run: |
+          rm -rf ~/.triton
 
       - *run-lit-tests-step
 
@@ -403,8 +410,7 @@ jobs:
 
       - name: Clean up caches
         run: |
-          rm -rf ~/.triton
-          rm -rf ~/.cache
+          rm -rf ~/.triton/cache
 
   Build-Tests:
     needs: Runner-Preparation
